ALTER TABLE `delivery_information`
CHANGE COLUMN `ADDRESS_HOUSE` `ADDRESS_HOUSE` VARCHAR(10) NULL DEFAULT NULL ,
CHANGE COLUMN `ADDRESS_DOOR` `ADDRESS_DOOR` VARCHAR(10) NULL DEFAULT NULL ,
CHANGE COLUMN `ADDRESS_FLOOR` `ADDRESS_FLOOR` VARCHAR(10) NULL DEFAULT NULL ;