ALTER TABLE `delivery_information`
ADD COLUMN `ADDRESS_HOUSE` INT NULL AFTER `time_range`,
ADD COLUMN `ADDRESS_DOOR` INT NULL AFTER `ADDRESS_HOUSE`,
ADD COLUMN `ADDRESS_FLOOR` INT NULL AFTER `ADDRESS_DOOR`;
