CREATE TABLE `PRICE_DIAPASON` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` BIGINT(20) NOT NULL,
  `PRICE_FROM` INT(20) NOT NULL,
  `PRICE_TO` INT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PRICE_DIAPASON_ITEMID_idx` (`ITEM_ID` ASC),
  CONSTRAINT `fk_PRICE_DIAPASON_ITEMID`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `liberty-jam`.`item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
