ALTER TABLE `order`
CHANGE COLUMN `DATE_CREATED` `DATE_CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '' ;

ALTER TABLE `order`
CHANGE COLUMN `STATUS` `STATUS` INT(11) NULL DEFAULT 0 COMMENT '' ;

ALTER TABLE `order`
CHANGE COLUMN `PAYMENT_NUMBER` `PAYMENT_NUMBER` VARCHAR(100) NULL DEFAULT NULL COMMENT '' ;


ALTER TABLE `order`
CHANGE COLUMN `PAYMENT_NUMBER` `PAYMENT_TYPE` INT(20) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN `CONFIRMATION_NUMBER` `CONFIRMATION_NUMBER` VARCHAR(50) NULL DEFAULT NULL COMMENT '' ;
