CREATE TABLE `ITEM_HAS_ACCESORY` (
  `ACCESORY_ID` BIGINT(20) NOT NULL,
  `ITEM_ID` BIGINT(20) NOT NULL,
  INDEX `FK_ITEM_HAS_ACCESORY_ACCID_idx` (`ACCESORY_ID` ASC),
  INDEX `FK_ITEM_HAS_ACCESORY_ITEMID_idx` (`ITEM_ID` ASC),
  CONSTRAINT `FK_ITEM_HAS_ACCESORY_ACCID`
    FOREIGN KEY (`ACCESORY_ID`)
    REFERENCES `ITEM_ACCESORIES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ITEM_HAS_ACCESORY_ITEMID`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
