CREATE TABLE content_pages (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `TITLE` VARCHAR(45) NULL COMMENT '',
  `CONTENT` VARCHAR(2000) NULL COMMENT '',
  `MENU_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '');
